### ISSUE TITLE
Can we build a test that asks students to create/use a generator?

### ISSUE THREAD

**Issue by baschenbrenner** [learn-co-curriculum/python-p3-comprehensions-and-generators#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195252?module_item_id=439019

### Concern

n/a

### Additional Context

I found the two tests very easy - one line of code - i thought I would challenge myself by trying to use a generator and was unable to pass the tests using the generator. Not sure if there is a different test that might fit better or a context that might show where a generator is useful if the end product is returning an array. Maybe a test where they have to print something out?

**Comment by professor-ben** [comment]
Hey Ben,

After discussing this a bit with Prabhdip, I think we're going to add something to this lesson to say that we'll work with generators when we introduce file input/output and databases later in phase 3.

I think it's still valuable to introduce generators here because one of the most common syntax goofs in Python is creating a generator instead of a list comprehension. I will make it more clear in this lesson that we will explore them more later on in phase 3.

-Other Ben
